package gitops

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/quaywin/agys/pkg/profile"
)

// GitClient abstracts interactions with the local git repository.
type GitClient interface {
	IsRepository(dir string) bool
	StageTrackedFiles(dir string) error
	StageAllFiles(dir string) error
	GetStagedFiles(dir string) ([]string, error)
	GetStagedDiff(dir string) (diff string, stat string, err error)
	Commit(dir string, message string) error
	Push(dir string) error
}

// AIReviewer abstracts the AI code review and commit message generator.
type AIReviewer interface {
	ReviewAndGenerate(ctx context.Context, profileDir string, stagedFiles []string, diff, stat, userMsg string, noCheck bool, model, effort, prompt string) (checkSummary, commitMessage string, err error)
}

// CommitOptions captures all CLI parameters for the commit workflow.
type CommitOptions struct {
	ProfileName string
	Message     string
	All         bool
	StageAll    bool
	Yes         bool
	Push        bool
	NoCheck     bool
	DryRun      bool
	Model       string
	Effort      string
	Prompt      string
	WorkingDir  string
}

// Service defines the interface for executing an AI-assisted commit.
type Service interface {
	Execute(ctx context.Context, opts CommitOptions) error
}

type defaultService struct {
	git      GitClient
	reviewer AIReviewer
	in       io.Reader
	out      io.Writer
	errOut   io.Writer
}

// NewService creates a new GitOps Commit Service.
func NewService(git GitClient, reviewer AIReviewer, in io.Reader, out io.Writer, errOut io.Writer) Service {
	if git == nil {
		git = NewDefaultGitClient()
	}
	if reviewer == nil {
		reviewer = NewDefaultAIReviewer()
	}
	if in == nil {
		in = os.Stdin
	}
	if out == nil {
		out = os.Stdout
	}
	if errOut == nil {
		errOut = os.Stderr
	}
	return &defaultService{
		git:      git,
		reviewer: reviewer,
		in:       in,
		out:      out,
		errOut:   errOut,
	}
}

func (s *defaultService) Execute(ctx context.Context, opts CommitOptions) error {
	// 1. Check if inside a git repository
	if !s.git.IsRepository(opts.WorkingDir) {
		return fmt.Errorf("not a git repository (or any of the parent directories)")
	}

	// 2. Stage files if requested
	if opts.StageAll {
		if err := s.git.StageAllFiles(opts.WorkingDir); err != nil {
			return err
		}
	} else if opts.All {
		if err := s.git.StageTrackedFiles(opts.WorkingDir); err != nil {
			return err
		}
	}

	// 3. Inspect staged files
	stagedFiles, err := s.git.GetStagedFiles(opts.WorkingDir)
	if err != nil {
		return err
	}
	if len(stagedFiles) == 0 {
		fmt.Fprintln(s.out, "No staged changes found. Use `git add <files>` to stage changes before committing.")
		return nil
	}

	// 4. Resolve target profile
	targetProfile, err := s.resolveProfile(ctx, opts.ProfileName)
	if err != nil {
		return err
	}

	profileDir, err := profile.GetProfileDir(targetProfile)
	if err != nil {
		return err
	}

	// 5. Get diff and stat
	diff, stat, err := s.git.GetStagedDiff(opts.WorkingDir)
	if err != nil {
		return err
	}

	fmt.Fprintf(s.errOut, "[agys] Inspecting %d staged file(s) under profile %q...\n", len(stagedFiles), targetProfile)

	var finalMessage string
	var checkSummary string

	if opts.NoCheck && opts.Message != "" {
		finalMessage = opts.Message
		checkSummary = "Skipped (--no-check specified)."
	} else if opts.NoCheck {
		checkSummary = "Skipped (--no-check specified)."
	} else {
		checkCtx, cancelCheck := context.WithTimeout(ctx, 90*time.Second)
		var revErr error
		checkSummary, finalMessage, revErr = s.reviewer.ReviewAndGenerate(checkCtx, profileDir, stagedFiles, diff, stat, opts.Message, opts.NoCheck, opts.Model, opts.Effort, opts.Prompt)
		cancelCheck()
		if revErr != nil {
			fmt.Fprintf(s.errOut, "[agys] Warning: AI commit check failed (%v).\n", revErr)
			if opts.Message != "" {
				finalMessage = opts.Message
			}
			checkSummary = "AI check unavailable."
		}
	}

	if strings.TrimSpace(finalMessage) == "" {
		if !opts.Yes {
			reader := bufio.NewReader(s.in)
			fmt.Fprint(s.out, "AI was unable to generate a commit message. Enter custom commit message: ")
			customMsg, readErr := reader.ReadString('\n')
			if readErr != nil && len(customMsg) == 0 {
				return fmt.Errorf("commit failed: no commit message provided")
			}
			customMsg = strings.TrimSpace(customMsg)
			if customMsg == "" {
				return fmt.Errorf("commit message cannot be empty")
			}
			finalMessage = customMsg
		} else {
			return fmt.Errorf("commit failed: no commit message provided or generated by AI")
		}
	}

	useColor := os.Getenv("NO_COLOR") == ""
	hasSecurityRisk := profile.ContainsSecurityRisk(checkSummary)

	// Display Code Review Summary
	if checkSummary != "" {
		if hasSecurityRisk {
			if useColor {
				fmt.Fprintln(s.out, "\n\033[1;31m┌────────────────────────────────────────────────────────────────────────┐\033[0m")
				fmt.Fprintln(s.out, "\033[1;31m│  ⚠️  SECURITY WARNING: Potential secrets or security risks detected!   │\033[0m")
				fmt.Fprintln(s.out, "\033[1;31m└────────────────────────────────────────────────────────────────────────┘\033[0m")
				fmt.Fprintln(s.out, "\033[1;31m--- Code Review Summary (Security Risk Detected!) ---\033[0m")
			} else {
				fmt.Fprintln(s.out, "\n[!] SECURITY WARNING: Potential secrets or security risks detected!")
				fmt.Fprintln(s.out, "--- Code Review Summary ---")
			}
		} else {
			if useColor {
				fmt.Fprintln(s.out, "\n\033[1;36m--- Code Review Summary ---\033[0m")
			} else {
				fmt.Fprintln(s.out, "\n--- Code Review Summary ---")
			}
		}
		fmt.Fprintln(s.out, checkSummary)
	}

	// Display Proposed Commit Message
	if useColor {
		fmt.Fprintln(s.out, "\n\033[1;32m--- Proposed Commit Message ---\033[0m")
	} else {
		fmt.Fprintln(s.out, "\n--- Proposed Commit Message ---")
	}
	fmt.Fprintln(s.out, finalMessage)
	fmt.Fprintln(s.out)

	if opts.DryRun {
		fmt.Fprintln(s.out, "[agys] Dry-run complete. No changes committed.")
		return nil
	}

	// If security risk is detected, bypass -y/--yes to force confirmation
	if hasSecurityRisk && opts.Yes {
		fmt.Fprintln(s.out, "[agys] ⚠️  Security warning detected in staged changes! Bypassing -y/--yes to require explicit confirmation.")
		opts.Yes = false
	}

	// Ask for confirmation
	if !opts.Yes {
		reader := bufio.NewReader(s.in)
		fmt.Fprint(s.out, "Commit with this message? [Y/n/e(dit)]: ")
		input, readErr := reader.ReadString('\n')
		if readErr != nil && len(input) == 0 {
			return fmt.Errorf("cancelled")
		}
		input = strings.TrimSpace(strings.ToLower(input))

		if input == "n" || input == "no" {
			fmt.Fprintln(s.out, "Commit cancelled.")
			return nil
		} else if input == "e" || input == "edit" {
			fmt.Fprint(s.out, "Enter custom commit message: ")
			customMsg, _ := reader.ReadString('\n')
			customMsg = strings.TrimSpace(customMsg)
			if customMsg == "" {
				return fmt.Errorf("commit message cannot be empty")
			}
			finalMessage = customMsg
		}
	}

	// Execute Git Commit
	fmt.Fprintf(s.out, "[agys] Executing git commit...\n")
	if err := s.git.Commit(opts.WorkingDir, finalMessage); err != nil {
		return err
	}

	// Push if requested
	if opts.Push {
		fmt.Fprintf(s.out, "[agys] Executing git push...\n")
		return s.git.Push(opts.WorkingDir)
	}

	return nil
}

func (s *defaultService) resolveProfile(ctx context.Context, name string) (string, error) {
	if name == "" {
		current, err := profile.GetCurrent()
		if err != nil {
			return "", err
		}
		if current != "" {
			name = current
		} else {
			name = profile.AutoProfileKeyword
		}
	}

	if profile.IsAuto(name) {
		selected, score, err := profile.SelectBestProfile(ctx)
		if err != nil {
			return "", fmt.Errorf("auto profile selection failed: %w", err)
		}
		scoreStr := fmt.Sprintf("%.1f%%", score*100)
		if score < 0 {
			scoreStr = "N/A"
		}
		fmt.Fprintf(s.errOut, "[agys] Auto-selected profile %q (5h Gemini quota: %s)\n", selected, scoreStr)
		return selected, nil
	}

	exists, _, err := profile.Exists(name)
	if err != nil {
		return "", err
	}
	if !exists {
		return "", fmt.Errorf("profile %q does not exist. Use `agys add %s` to create it", name, name)
	}
	return name, nil
}

// DefaultGitClient implements GitClient via pkg/profile.
type DefaultGitClient struct{}

// NewDefaultGitClient creates a new DefaultGitClient.
func NewDefaultGitClient() *DefaultGitClient {
	return &DefaultGitClient{}
}

func (g *DefaultGitClient) IsRepository(dir string) bool {
	return profile.IsGitRepository(dir)
}

func (g *DefaultGitClient) StageTrackedFiles(dir string) error {
	return profile.StageTrackedFiles(dir)
}

func (g *DefaultGitClient) StageAllFiles(dir string) error {
	return profile.StageAllFiles(dir)
}

func (g *DefaultGitClient) GetStagedFiles(dir string) ([]string, error) {
	return profile.GetStagedFiles(dir)
}

func (g *DefaultGitClient) GetStagedDiff(dir string) (string, string, error) {
	diff, err := profile.GetCompactStagedDiff(dir)
	if err != nil {
		diff, err = profile.GetStagedDiff(dir)
		if err != nil {
			return "", "", err
		}
	}
	stat, _ := profile.GetStagedDiffStat(dir)
	return diff, stat, nil
}

func (g *DefaultGitClient) Commit(dir string, message string) error {
	return profile.ExecuteGitCommit(dir, message)
}

func (g *DefaultGitClient) Push(dir string) error {
	return profile.ExecuteGitPush(dir)
}

// DefaultAIReviewer implements AIReviewer using profile.RunAgyCommitCheck.
type DefaultAIReviewer struct{}

// NewDefaultAIReviewer creates a new DefaultAIReviewer.
func NewDefaultAIReviewer() *DefaultAIReviewer {
	return &DefaultAIReviewer{}
}

func (r *DefaultAIReviewer) ReviewAndGenerate(ctx context.Context, profileDir string, stagedFiles []string, diff, stat, userMsg string, noCheck bool, model, effort, prompt string) (string, string, error) {
	result, err := profile.RunAgyCommitCheck(ctx, profileDir, stagedFiles, diff, stat, userMsg, noCheck, model, effort, prompt)
	if err != nil {
		return "", "", err
	}
	return result.CheckSummary, result.CommitMessage, nil
}
